apiVersion: v1
kind: Service
metadata:
  name: neo4j-centralus-public-lb
  namespace: neo4j
  labels:
    app: neo4j
    app.kubernetes.io/name: neo4j
    app.kubernetes.io/instance: neo4j-centralus
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "40.78.168.78"
spec:
  type: LoadBalancer
  loadBalancerIP: 40.78.168.78
  publishNotReadyAddresses: true
  externalTrafficPolicy: Cluster
  selector:
    helm.neo4j.com/instance: neo4j-centralus
  ports:
    - name: http
      port: 7474
      targetPort: 7474
      protocol: TCP
    - name: bolt
      port: 7687
      targetPort: 7687
      protocol: TCP
