kind: StorageClass
#Very Fast and Very Expansive
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-io2-xfs
provisioner: ebs.csi.aws.com
#provisioner: kubernetes/aws-ebs
parameters:
  type: io2
  csi.storage.k8s.io/fstype: xfs
  iopsPerGB: "20"
reclaimPolicy: Retain
allowVolumeExpansion: true
#wait for First Consumer because we need the data to be in the same AZ as the pod
volumeBindingMode: WaitForFirstConsumer
