kind: StorageClass
#standard gp3 storage class - use for logs mount or all for a in memory or low to medium write volume
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-gp3-xfs
provisioner: ebs.csi.aws.com
#provisioner: kubernetes/aws-ebs
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: xfs
reclaimPolicy: Retain
allowVolumeExpansion: true
#wait for First Consumer because we need the data to be in the same AZ as the pod
volumeBindingMode: WaitForFirstConsumer
