kind: "PersistentVolume"
apiVersion: "v1"
metadata:
  # n.b. persistent volumes don't seem to belong to namespaces
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ template "neo4j.appName" . }}"
    helm.neo4j.com/volume-role: "data"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "{{ required "capacity.storage is required (e.g. 10Gi)" .Values.capacity.storage }}"
  hostPath:
    path: "{{ required "hostPath is required (e.g. /tmp/neo4j)" .Values.hostPath }}"
    type: Directory
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ template "neo4j.appName" . }}"
    helm.neo4j.com/volume-role: "data"
spec:
  storageClassName: ""
  volumeName: "{{ .Release.Name }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ required "capacity.storage is required (e.g. 10Gi)" .Values.capacity.storage }}"
