{{- /* In almost all cases the selector should be unspecified and the default selector should be used. */ -}}
{{- template "neo4j.checkPortMapping" . -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "neo4j.name" $ }}-headless"
  namespace: "{{ .Release.Namespace }}"
  labels:
    helm.neo4j.com/neo4j.name: "{{ template "neo4j.name" $ }}"
    app: "{{ template "neo4j.name" . }}"
  {{- with .Values.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  ports:
    {{- with .Values.ports }}
    {{- if .http.enabled }}
    - protocol: TCP
      port: {{ .http.port | default 7474 }}
      targetPort: 7474
      name: http
    {{- end }}
    {{- if .https.enabled }}
    - protocol: TCP
      port: {{ .https.port | default 7473 }}
      targetPort: 7473
      name: https
    {{- end }}
    {{- if .bolt.enabled }}
    - protocol: TCP
      port: {{ .bolt.port | default 7687 }}
      targetPort: 7687
      name: tcp-bolt
    {{- end }}
    {{ with .backup }}
    {{- if .enabled }}
    - protocol: TCP
      port: {{ .port | default 6362 }}
      targetPort: 6362
      name: tcp-backup
    {{- end }}
    {{- end }}
    {{- end }}

  selector:
    app: "{{ template "neo4j.name" . }}"
    {{- with .Values.selector }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
