kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mrc-neo4-ssc-azurefile
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0770
  - file_mode=0770
  - uid=7474
  - gid=7474
  - mfsymlinks
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - nosharesock
parameters:
  skuName: Premium_LRS