apiVersion: v1
# This is the primary load balancer - serves the 3 core members
# This requires the following in the nodepool definition of eksctl yaml
#   iam:
#     withAddonPolicies:
#        ebs: true
#        efs: true
#        awsLoadBalancerController: true
kind: Service
metadata:
  name: neo4j-core-lb

  labels:
    app: neo4j-core
    kubernetes.azure.com/nodepool-type: "primary"
    helm.neo4j.com/service: neo4j

  # https://cloud-provider-azure.sigs.k8s.io/topics/loadbalancer/#loadbalancer-annotations
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/azure-load-balancer-mode: default
    #service.beta.kubernetes.io/azure-load-balancer-ipv4: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
    #service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    #service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443, 7687
    #service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:766746056086:certificate/8781b4f1-e8b1-4d0b-ab05-1fe0523e527a
    #service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=true,stickiness.type=source_ip

spec:
  type: LoadBalancer
  #loadBalancerIP: 10.151.8.87
  ports:
  - name: bolt
    port: 7687
    protocol: TCP
    targetPort: 7687
  - name: http
    port: 7474
    protocol: TCP
    targetPort: 7474
  selector:
    app: neo4j
    kubernetes.azure.com/nodepool-type: "primary"
    #helm.neo4j.com/clustering: 'true'
  sessionAffinity: None
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
